In [1]:
from math import *
import numpy as np

In [2]:
print('Opérations de base 	:')
tab = np.array([(5,2,7),(3,8,6)])  # Construction d'une matrice tab de 2 lignes et 3 colonnes
print('a = ',tab)                  # affichage de tous les éléments de la matrice tab
print('b = ',tab[1,2])             # affichage de l'élément situé à la 2nde ligne et 3ème colonne i.e. 6
print('c = ',tab[1])               # affichage des éléments situés à la 2nde ligne (ou tab[1,:])
print('d = ',tab[:,1])             # affichage des éléments situés à la 2nde colonne 
print('e = ',2 * tab)              # affichage la matrice résultante du calcul 2*tab (tous les éléments doublés) 
print('f = ',tab / 2)              # affichage la matrice résultante du calcul tab/2 (tous les éléments divisés par 2) 
print('g = ',tab // 2)             # affichage la matrice résultante du calcul du quotient de chaque terme de tab par 2 
print('h = ',tab - 1)              # affichage la matrice résultante du calcul de la différence de chaque terme de tab avec 1 
print('i = ',tab ** 2)             # affichage la matrice résultante du calcul du carré de chaque terme de tab

Opérations de base 	:
a =  [[5 2 7]
 [3 8 6]]
b =  6
c =  [3 8 6]
d =  [2 8]
e =  [[10  4 14]
 [ 6 16 12]]
f =  [[2.5 1.  3.5]
 [1.5 4.  3. ]]
g =  [[2 1 3]
 [1 4 3]]
h =  [[4 1 6]
 [2 7 5]]
i =  [[25  4 49]
 [ 9 64 36]]


In [3]:
print()                     # ligne vierge
print('numpy zeros')
z1 = np.zeros(5)            # vecteur de 5 éléments nuls
print('z1 = ',z1)
z2 = np.zeros((5,3))        # matrice nulle de dimension 5 lignes et 3 colonnes 
print('z2 =\n ',z2)


numpy zeros
z1 =  [0. 0. 0. 0. 0.]
z2 =
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print()
print('numpy ones')
o1 = np.ones(4)            # vecteur de 4 éléments égaux à 1
print('o1 = ',o1)
o2 = np.ones((2,3))        # matrice de dimension 2 lignes et 3 colonnes remplie de 1
print('o2 =\n ',o2)


numpy ones
o1 =  [1. 1. 1. 1.]
o2 =
  [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print()
print('numpy reshape')
a1 = np.arange(6)                       # créer une liste de 6 éléments ordonnés de 0 à 5
print( 'a1 = ',a1)
a2 = np.arange(6).reshape(2,3)          # redimensionner le tableau en 2 lignes et 3 colonnes
print('a2 =\n ',a2)
a3 = np.arange(1,16,4.2)                # créer une liste de valeur 1 à 16 par pas de 4.2 (borne supérieure non atteinte)
print('a3 = ',a3)
a4 = np.arange(1,16,4.2).reshape(2,2)   # redimensionner le tableau précédent en 2 lignes et 2 colonnes
print('a4 =\n ',a4)
a5 = np.arange(10)                      # créer une liste de 10 éléments ordonnés de 0 à 9
print('a5 = ',a5[2:9:3])   


numpy reshape
a1 =  [0 1 2 3 4 5]
a2 =
  [[0 1 2]
 [3 4 5]]
a3 =  [ 1.   5.2  9.4 13.6]
a4 =
  [[ 1.   5.2]
 [ 9.4 13.6]]
a5 =  [2 5 8]


In [6]:
print()
print('numpy eye')
e1 = np.eye(2,3)                 # création de la matrice identité de taille 2x3
print('e1 = ',e1)
e2 = np.eye(3,3)                 # création de la matrice identité d'ordre 3
print('e2 = ',e2)
e3 = np.eye(4,3)                 # création de la matrice identité de taille 4x3
print('e3 = ',e3)


numpy eye
e1 =  [[1. 0. 0.]
 [0. 1. 0.]]
e2 =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
e3 =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [7]:
print()
print('numpy diag')
vect = np.arange(5) + 1           # création d'une liste de 5 éléments ordonnés de 0 à 4 auxquels on ajouté 1 individuellement
print('vect = ',vect)
diag1 = np.diag(vect)             # création d'une matrice dont la diagonale est constituée des éléments du vecteur vect
print('diag1 =\n ',diag1)
diag2 = np.diag(vect,1)           # création d'une matrice dont la diagonale supérieure +1 est constituée des éléments du vecteur vect, d'ordre 6
print('diag2 =\n ',diag2)
diag3 = np.diag(vect,-1)          # création d'une matrice dont la diagonale inférieure -1 est constituée des éléments du vecteur vect, d'ordre 6
print('diag2 =\n ',diag3)


numpy diag
vect =  [1 2 3 4 5]
diag1 =
  [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
diag2 =
  [[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]
diag2 =
  [[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [8]:
print()
print('numpy random et array')
r = np.random.rand(5,4)         # création d'une matrice de taille 5x4 remplie de nbs aléatoires ds ]0; 1[
print('r =\n ',r)
l = np.array([1, 2, 2, 3, 0])   # vecteur de 5 éléments
print('l = ',l)  
c = np.array([3, 1, 2, 0, 1])   # vecteur de 5 éléments
print('c = ',c)
print('r[l,c] = ',r[l,c])       # application d'un masque à partir des 2 listes précédentes


numpy random et array
r =
  [[0.75105412 0.34234821 0.11351371 0.74607673]
 [0.79446924 0.89616495 0.09045216 0.95262243]
 [0.0180221  0.47527188 0.68143987 0.19504831]
 [0.41046903 0.60327764 0.82838909 0.49708927]
 [0.08356426 0.30176444 0.52915081 0.11252937]]
l =  [1 2 2 3 0]
c =  [3 1 2 0 1]
r[l,c] =  [0.95262243 0.47527188 0.68143987 0.41046903 0.34234821]


In [9]:
print()
print('numpy reshape et concatenate')
a = np.arange(4).reshape(2,2)   # création d'une liste de 4 éléments ordonnés de 0 à 3 
print('a =\n ',a)                 # combinée à un redimensionnement en matrice d'ordre 2
b = 4 + np.arange(4).reshape(2,2) # création d'une liste de 4 éléments ordonnés de 4 (0+4) à 7 (3+4)
print('b =\n ',b)                   # combinée à un redimensionnement en matrice d'ordre 2
c = np.concatenate((a,b))        # concaténation verticale des 2 matrices précédentes
print('c =\n ',c)
d = np.concatenate((a,b), axis = 1) # concaténation horizontale des 2 matrices précédentes
print('d =\n ',d)


numpy reshape et concatenate
a =
  [[0 1]
 [2 3]]
b =
  [[4 5]
 [6 7]]
c =
  [[0 1]
 [2 3]
 [4 5]
 [6 7]]
d =
  [[0 1 4 5]
 [2 3 6 7]]


In [10]:
print()
print('numpy reshape et tile')
a6 = np.arange(4).reshape((2,2))
print('a6 =\n ',a6)
a7 = np.tile(a6, (2,3))   # duplication de la matrice précédente 2 fois en ligne et 3 fois en colonne
print('a7 =\n ',a7)


numpy reshape et tile
a6 =
  [[0 1]
 [2 3]]
a7 =
  [[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]


## Algèbre linéaire

In [11]:
import numpy.linalg as la

print()
print('numpy.linalg transpose')
M = np.array([[1,2],[3,4]])  # création d'une matrice statique
print('M =\n ',M)
T = np.transpose(M)         # transposition de la matrice précédente
print('T =\n ',T)


numpy.linalg transpose
M =
  [[1 2]
 [3 4]]
T =
  [[1 3]
 [2 4]]


In [12]:
print()
print('numpy.linalg det')
D = la.det(M)              # calcul d'un déterminant
print('det(M) = ', D)


numpy.linalg det
det(M) =  -2.0000000000000004


In [21]:
print()
print('numpy.linalg inv')
M = np.array([[1,2],[3,4]])
N = la.inv(M)              # calcul d'une matrice inverse
print('M = \n',M)             
print('inv(M) = \n ',N)


numpy.linalg inv
M = 
 [[1 2]
 [3 4]]
inv(M) = 
  [[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
print()


M = np.array([[1,2],[3,4]])
N = la.inv(M) 

print('numpy.linalg dot')
P=np.dot(M,N)         # calcul du produit matriciel M*N = instruction de vérification du résultat précédent
print('M * N = \n',P)


numpy.linalg dot
M * N = 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [15]:
print()
print('numpy.linalg eig')
[Val,Vect] = la.eig(M)  # calcul des éléments propres de la matrice M
print('Val = ',Val)
print('Vect =\n ', Vect)


numpy.linalg eig
Val =  [-0.37228132  5.37228132]
Vect =
  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [16]:
print()
print('numpy.linalg solve')
M = np.array([[1,2],[3,4]])
print('M = \n',M)
B = np.array([5, 6])   # construction d'un vecteur de longueur 2 (2nd membre de l'équation matricielle)
print('B = ',B)
X = la.solve(M,B)  # résolution du système linéaire M*X=B
print('X = ',X)
Y = np.dot(M,X)   # calcul du produit matriciel M*X = instruction de vérification du résultat précédent (Y=B)
print('M*X =\n ',Y)


numpy.linalg solve
M = 
 [[1 2]
 [3 4]]
B =  [5 6]
X =  [-4.   4.5]
M*X =
  [5. 6.]


# Fonction "kron"

In [17]:
print()
print('numpy kron et transpose')
n=5
a=np.arange(n)    # création d'une liste de 5 éléments ordonnés de 0 à 4
print(a)
b=np.ones((1,n))  # création d'un vecteur ligne de 5 éléments remplis de 1
print(b)
c=np.kron(a,b.transpose())  #
print(c)



numpy kron et transpose
[0 1 2 3 4]
[[1. 1. 1. 1. 1.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# Exemple de traitement de listes

In [18]:
print()
print('listes')

liste0 = [0,1,2,3,4,5,6]
liste1 = [ elt * elt for elt in liste0]  # expression de type "list comprehension"
                                        # chaque élément de la liste précédente élevé au carré
liste2 = [ element for element in liste1 if element % 2 == 0]


listes


# liste constitué des éléments de la liste précédente vérifiant un test de parité

In [19]:
print()
print(liste0)       # Affichage des listes résultats
print(liste1)
print(liste2)


[0, 1, 2, 3, 4, 5, 6]
[0, 1, 4, 9, 16, 25, 36]
[0, 4, 16, 36]


# Affectation de lignes à la Matlab

In [20]:
A = np.zeros((4,4))   # A matrice d'ordre 4 remplie de 0
S = np.arange(4)      # S vecteur ligne de 4 éléments ordonnés de 1 à 4
C = S ** 2            # C vecteur ligne, valeur = terme S correspondant élevé au carré
D = S ** 3            # D vecteur ligne, valeur = terme S correspondant à la puissance 3
E = S ** 4            # E vecteur ligne, valeur = terme S correspondant à la puissance 4

print('C = ',C)       # affichage vecteur résultat C
print('D = ',D)       # affichage vecteur résultat D
print('E = ',E)       # affichage vecteur résultat E
A[0,:] = C            # Affectation du vecteur C à la 1ère ligne de A
A[1,:] = D            # Affectation du vecteur D à la 2nde ligne de A
A[2,:] = E            # Affectation du vecteur E à la 3ème ligne de A
print('A =\n ',A)       # affichage de la matrice résultat


C =  [0 1 4 9]
D =  [ 0  1  8 27]
E =  [ 0  1 16 81]
A =
  [[ 0.  1.  4.  9.]
 [ 0.  1.  8. 27.]
 [ 0.  1. 16. 81.]
 [ 0.  0.  0.  0.]]
